#!/usr/bin/bash
#Author: Bishal singh -Anon4You
#Alienlkrishn

printf "\a\e[34m
#    #    #    #       ###    #       ### #     # #     # #     #
#   #    # #   #        #     #        #  ##    # #     #  #   #
#  #    #   #  #        #     #        #  # #   # #     #   # #
###    #     # #        #     #        #  #  #  # #     #    #
#  #   ####### #        #     #        #  #   # # #     #   # #
#   #  #     # #        #     #        #  #    ## #     #  #   #
#    # #     # ####### ###    ####### ### #     #  #####  #     #

\e[0mkali-linux inataller script by \e[32mAlienkrishn \e[0m

"
command -v x11-repo > /dev/null 2>&1 || { echo >&2 "x11-repo not found!, Installing... x11-repo"; apt install x11-repo -y 1; }
command -v xwayland > /dev/null 2>&1 || { echo >&2 "installing termux-x11"; apt install termux-x11-nightly xwayland dbus -y 1; }

CHROOT=$PREFIX/var/lib/proot-distro/installed-rootfs/debian

curl -LO https://raw.githubusercontent.com/Anon4You/kalilinux/main/xstart
mv xstart $PATH && chmod +x $PATH/xstart
echo "proot-distro login --user kali debian --shared-tmp" > $PATH/kalilinux
chmod +x $PATH/kalilinux


if [[ -d "$PREFIX/var/lib/proot-distro/installed-rootfs/debian"  ]]; then
    printf "\e[33;1mExisting debian found reseting it\e[0m"
    proot-distro reset debian
else
    echo -e "--- Installing requirements"
    apt update && apt upgrade -y
    apt install proot-distro -y
    echo -e "-- installing debian and converting to kali"
    proot-distro install debian
fi

rm $CHROOT/root/.bashrc 
cat > $CHROOT/root/.bashrc <<- EOF
apt-get update -y
apt install gnupg figlet sudo curl -y
useradd -m -s /bin/bash kali
echo "kali:kali" | chpasswd
echo "kali  ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/kali
rm -rf /etc/apt/sources.list
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list
curl -sSL https://archive.kali.org/archive-key.asc | apt-key add
mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d
apt-get update -y && apt-get dist-upgrade -y
apt-get install sudo figlet -y 
rm .bashrc
curl -LO https://raw.githubusercontent.com/Anon4You/kalilinux/main/.bashrc
cp .bashrc /home/kali
sleep 1
echo -e "
NOTE

just type kalilinux to login to kali
default password for sudo is kali
Author: Alienkrishn 

"
exit
EOF
proot-distro login debian
