#!/bin/bash
termux-x11 :1 &
sleep 2
env DISPLAY=:1 dbus-launch --exit-with-session xfce4-session > /dev/null 2>&1 
sleep 2
printf "Starting termux-x11\r" ; sleep 0.5
printf "Starting termux-x11.\r" ; sleep 0.5
printf "Starting termux-x11..\r" ; sleep 0.5
printf "Starting termux-x11...\r" ; sleep 0.5
printf "Starting termux-x11....\r" ; sleep 0.5
echo -e "\nTermux-x11 started."
